### PR TITLE
Remove data_ from Header<T>

### PR DESCRIPTION
**Pull request by LeonineKing1199**
Attempting to address https://github.com/LeonineKing1199/minivec/issues/2

### CODE REVIEW

**Comment by Plecra** [comment]
I mentioned it before, but you can make the alignment calculations much simpler by leaning on Rust a little. Is there a reason you chose not to use this approach?

```rust
pub struct MiniVec<T> {
    /// Safety: Either null or a valid pointer to the Inner owned by this MiniVec
    ptr: *mut Inner<T>,
}

/// Guarantees that `cap` `T`s have been allocated after this structure.
#[repr(C)]
struct Inner<T> {
    cap: usize,
    // Length of initialized elements in `data`
    len: usize,
    #[allow(unused)]
    data: [T; 0],
}

impl<T> Inner<T> {
    fn as_mut_slice(&mut self) -> &mut [T] {
        let ptr = unsafe {
            // Safety: The data region comes after a single Self allocation.
            // If it is empty, this will only be one byte past the allocation
            // This won't wrap, because self < usize::MAX - size_of::<Self>()
            (self as *mut Inner<T>).add(1) as *mut T
        };
        unsafe {
            // Safety: The data region contains at least self.len elements
            slice::from_raw_parts_mut(ptr, self.len)
        }
    }
}

impl<T> MiniVec<T> {
    /// Checks if the MiniVec's allocation has been created
    fn inner_mut(&mut self) -> Option<&mut Inner<T>> {
        if self.ptr.is_null() {
            None
        } else {
            Some(unsafe {
                /// Safety: ptr is valid so long as it isn't null
                &mut *self.ptr
            })
        }
    }
    /// Extracts a mutable slice of the entire vector.
    fn as_mut_slice(&mut self) -> &mut [T] {
        self.inner_mut().map_or(&mut [], |inner| inner.as_mut_slice())
    }
}
```
Using this layout removes the need for *any* of the alignment calculations, letting Rust handle it all instead and making the code way simpler.

**Comment by LeonineKing1199** [comment]
Is it safe to cast from `*mut Inner<T>` to `*mut T`? In C++, this would most assuredly be UB. Maybe even in C too.

Pointer arithmetic in those langs typically implies some kind of an array object. This seems like a strong jump in types.

The reason `*mut u8` was chosen is because byte types are allowed to alias any and all objects.

**Comment by Plecra** [comment]
Raw pointers don't actually have any validity requirements. They can be any `usize`, you only have to be careful about using them.

The pointer calculation is functionally identical to this:

```rust
(self as *mut Inner<T> as *mut u8)
    .add(size_of::<Inner<T>>()) as *mut T
```

**Comment by LeonineKing1199** [comment]
That's good to know.

Being completely honest, I don't really know Rust all that well. `MiniVec` started out primarily as a learning project and I'm still picking up Rust all the time.

I learned a lot by reading your Rust code but because `MiniVec` is a low-level component doing low-level things, I want to keep most things "simple". Here simple = the same way C is simple.

```rust
/// Guarantees that `cap` `T`s have been allocated after this structure.
#[repr(C)]
```
I'm not stoked that we need this because it means we're relying on implicit object layout which we can't control. In the ideal case, we'd have exactly control over the layout of everything we touch with regards to the allocation.

```rust
#[allow(unused)]
data: [T; 0],
```
I'm not happy we need the `#[allow(unused)]` right here. I get why it's there but the way the code works now, it isn't required.

I'm not too sold on the monadic approach via Optional for this either. Imo, the code's already pretty clear but I'd be open to seeing what refactoring more of the current existing code to use Optional would look like.

Fundamentally, a `*mut u8` pointer is the most simple construct. We really only have two problems to solve.

1. making sure the alignment of the allocation works for both T and `Header`/`Inner`
2. finding the location where we write the array to

There's really nothing more to solve in this regard and I'd prefer to keep things explicit instead of implicit because we can easily verify everything. It's also a problem with small-scope so it's an acceptable trade-off of maintenance burden and benefit.

**Comment by Plecra** [comment]
I only proposed the changes because I find them "simpler", which is naturally completely subjective. I suspect people who are used to Rust would also find it easier to understand since they'll already know about the guarantees Rust makes.

As for your concerns, I don't think we actually need that `repr(C)`. I just typically use it when writing pointer code since it's more straightforward than `repr(Rust)`. Allowing lints like `unused` is just a natural part of unsafe code imo (`clippy::cast_ptr_alignment` is much harder to verify).

I might make a PR to demonstrate how `Option` can help. Simply put, it lets you make that guarantee `` `cap` `T`s have been allocated after this structure.`` (and that `len` of them are initialised) in the type system, and encapsulate the unsafety.

**Comment by LeonineKing1199** [comment]
> That is to say, I think of *mut u8 as the most complex type. It tells me nothing about the state of the data, and I need to keep track of what it means at a point in time rather than its fundamental properties.

I actually don't disagree.

But also consider this, `Inner<T>` still doesn't imply that after it there's a `[T]`. It contains a `[T; 0]` sure but that only guarantees the alignment of the type itself.

The real thing that's confusing is that we're storing two data structures in this buffer and we use offsets to grab pointers to those objects.

But again, `MiniVec` is very small in terms of what it's doing here. There's the header and the array and that's it! If we were reimplementing something like a heap, I'd understand more. But for this, there's bigger fish to fry!

For example, if you really wanna be a hero, we need an implementation of `DrainFilter`. The `From` impl is also kind of sloppy and needs to be cleaned up as well. We also could add support of ZSTs.

In the ideal case, we'd have all the tests commented in in `tests/vec.rs`. That's a copy-paste of the actual `std::vec::Vec` test file ripped from GitHub (which also made licensing kind of funky for that file).

I'd also be interested in seeing if we benefit from making the `buf` pointer `NonNull` as well.

**Comment by LeonineKing1199** [comment]
I'm going to go ahead and the merge the PR because it accomplishes what it set out to do and I don't wanna be blocked on it.

If we wanna make any other changes, we should just open up a new issue/PR combo and then we can take it from there. I feel like there's already been a good bit of useful discussion here!

**Pull request merged**
